"""记忆领域核心：模型、文档结构与确定性写入规则。"""

from memory.core.formation import (
    MEMORY_SCHEMA_VERSION,
    EpisodeSalienceGate,
    MemoryCandidateRegistry,
    MemoryCandidateSchema,
    RuleFallbackExtractor,
    SalienceDecision,
    SalienceFactor,
)
from memory.core.model import (
    ABSENT,
    AbsentPath,
    DocumentChangeEvent,
    DocumentEditKind,
    DocumentEditPlan,
    DocumentRegistrationState,
    ManagedDocument,
    MemoryCandidateKind,
    MemoryDocument,
    MemoryDocumentKind,
    MemoryEditProposal,
    PresentPath,
    QuarantinedDocument,
    RawPathState,
    RegistrationStatus,
    ScanGeneration,
    UnmanagedDocument,
    UnsafePath,
)
from memory.core.structure.frontmatter import (
    FrontMatterError,
    MissingDocumentId,
    MissingFrontMatter,
    ParsedFrontMatter,
    adopt_raw_document,
    matches_adopted_source,
    new_document_id,
    parse_front_matter,
    render_new_document,
    validate_document_id,
)
from memory.core.structure.path_policy import MemoryDocumentPathPolicy
from memory.core.write.router import MemoryDocumentRouter

__all__ = [
    "ABSENT",
    "MEMORY_SCHEMA_VERSION",
    "AbsentPath",
    "DocumentChangeEvent",
    "DocumentEditKind",
    "DocumentEditPlan",
    "DocumentRegistrationState",
    "EpisodeSalienceGate",
    "FrontMatterError",
    "ManagedDocument",
    "MemoryCandidateKind",
    "MemoryCandidateRegistry",
    "MemoryCandidateSchema",
    "MemoryDocument",
    "MemoryDocumentKind",
    "MemoryDocumentPathPolicy",
    "MemoryDocumentRouter",
    "MemoryEditProposal",
    "MissingDocumentId",
    "MissingFrontMatter",
    "ParsedFrontMatter",
    "PresentPath",
    "QuarantinedDocument",
    "RawPathState",
    "RegistrationStatus",
    "RuleFallbackExtractor",
    "SalienceDecision",
    "SalienceFactor",
    "ScanGeneration",
    "UnmanagedDocument",
    "UnsafePath",
    "adopt_raw_document",
    "matches_adopted_source",
    "new_document_id",
    "parse_front_matter",
    "render_new_document",
    "validate_document_id",
]
